#!/bin/sh
# Install the sdlc-crew skills and persona agents for the harnesses on this machine.
#
# usage: install.sh [--harness NAME]... [--project] [--dry-run] [--quiet]
#
#   --harness NAME  Install for one harness only: claude-code, codex, gemini, or
#                   copilot. Repeat the flag for more than one. Without the flag, the
#                   script installs for each harness whose config directory exists.
#   --project       Install into the current repository instead of the home
#                   directory, so the files can be committed and shared.
#   --dry-run       Print what the script would do. Change nothing.
#
# The script links the skills, so a `git pull` in this repository updates them. It
# renders the Codex agent files, because Codex needs the skill text inline. It never
# replaces a file that it did not create.
set -eu

REPO_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
SKILLS_DIR="$REPO_DIR/skills"
ADAPTERS_DIR="$REPO_DIR/adapters"
MARKER="generated by sdlc-crew install.sh"
DRY_RUN=0
PROJECT=0
HARNESSES=""
status=0

usage() {
    sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
}

log() {
    printf '%s\n' "$*"
}

warn() {
    printf '%s\n' "$*" >&2
    status=1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --harness)
            [ $# -ge 2 ] || { warn "--harness needs a value"; exit 2; }
            HARNESSES="$HARNESSES $2"
            shift 2
            ;;
        --project) PROJECT=1; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) warn "unknown argument: $1"; usage >&2; exit 2 ;;
    esac
done

if [ "$PROJECT" -eq 1 ]; then
    PROJECT_DIR=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
fi

CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
GEMINI_DIR="$HOME/.gemini"
COPILOT_DIR="$HOME/.copilot"
AGENTS_SKILLS_DIR="$HOME/.agents/skills"

if [ -z "$HARNESSES" ]; then
    [ -d "$CLAUDE_DIR" ] && HARNESSES="$HARNESSES claude-code"
    [ -d "$CODEX_DIR" ] && HARNESSES="$HARNESSES codex"
    [ -d "$GEMINI_DIR" ] && HARNESSES="$HARNESSES gemini"
    [ -d "$COPILOT_DIR" ] && HARNESSES="$HARNESSES copilot"
fi

if [ -z "$HARNESSES" ]; then
    warn "No harness found. Install Claude Code, Codex CLI, Gemini CLI, or GitHub Copilot CLI first, or pass --harness."
    exit 1
fi

run() {
    if [ "$DRY_RUN" -eq 1 ]; then
        log "would: $*"
    else
        "$@"
    fi
}

ensure_dir() {
    [ -d "$1" ] || run mkdir -p "$1"
}

link() {
    src="$1"
    dest="$2"
    ensure_dir "$(dirname "$dest")"
    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        log "current: $dest"
    elif [ -e "$dest" ] || [ -L "$dest" ]; then
        warn "skipped: $dest exists and is not a link to this repository. Remove it, then run this script again."
    else
        run ln -s "$src" "$dest"
        log "linked:  $dest -> $src"
    fi
}

link_skills() {
    for skill in "$SKILLS_DIR"/*/; do
        skill="${skill%/}"
        link "$skill" "$1/$(basename "$skill")"
    done
}

link_agents() {
    src_dir="$1"
    dest_dir="$2"
    suffix="$3"
    for agent in "$src_dir"/*"$suffix"; do
        link "$agent" "$dest_dir/$(basename "$agent")"
    done
}

owned_file() {
    [ -f "$1" ] && head -1 "$1" | grep -q "$MARKER"
}

write_generated() {
    dest="$1"
    ensure_dir "$(dirname "$dest")"
    if [ -e "$dest" ] && ! owned_file "$dest"; then
        warn "skipped: $dest exists and was not generated by this script. Remove it, then run this script again."
        return
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        log "would: write $dest"
        cat >/dev/null
    else
        cat > "$dest"
        log "wrote:   $dest"
    fi
}

skill_body() {
    awk 'BEGIN{fm=0} /^---[[:space:]]*$/{fm++; next} fm>=2{print}' "$1"
}

skill_description() {
    awk '/^description:/{sub(/^description:[[:space:]]*/,""); print; exit}' "$1"
}

config_model() {
    role="$1"
    file="${PROJECT_DIR:-.}/.sdlc-crew.yaml"
    [ -f "$file" ] || return 0
    awk -v role="$role" '
        /^models:/ {in_models=1; next}
        in_models && /^[^ ]/ {in_models=0}
        in_models && $1 == role ":" {print $2; exit}
    ' "$file" | tr -d '"'"'"
}

render_codex_agent() {
    tmpl="$1"
    dest="$2"
    name=$(basename "$tmpl" .toml.tmpl)
    skill="$SKILLS_DIR/$name/SKILL.md"
    role=$(awk '/^  role:/{print $2; exit}' "$skill")
    case "$role" in
        plan|build|review) model=$(config_model "$role") ;;
        *) model="" ;;
    esac
    if [ -n "$model" ] && [ "$model" != "inherit" ]; then
        model_line="model = \"$model\""
    else
        model_line=""
    fi
    if grep -q "'''" "$skill"; then
        warn "skipped: $skill holds three single quotes, which the Codex agent file cannot hold."
        return
    fi
    description=$(skill_description "$skill" | sed 's/"/\\"/g')
    {
        while IFS= read -r line; do
            case "$line" in
                *@@DESCRIPTION@@*) printf '%s\n' "$line" | sed "s|@@DESCRIPTION@@|$(printf '%s' "$description" | sed 's/[|&]/\\&/g')|" ;;
                @@MODEL@@) [ -n "$model_line" ] && printf '%s\n' "$model_line" ;;
                @@BODY@@) skill_body "$skill" ;;
                *) printf '%s\n' "$line" ;;
            esac
        done < "$tmpl"
    } | write_generated "$dest"
}

copy_generated() {
    src="$1"
    dest="$2"
    { printf '<!-- %s -->\n' "$MARKER"; cat "$src"; } | write_generated "$dest"
}

install_claude_code() {
    if [ "$PROJECT" -eq 1 ]; then
        link_skills "$PROJECT_DIR/.claude/skills"
        link_agents "$ADAPTERS_DIR/claude-code/agents" "$PROJECT_DIR/.claude/agents" .md
    else
        link_skills "$CLAUDE_DIR/skills"
        link_agents "$ADAPTERS_DIR/claude-code/agents" "$CLAUDE_DIR/agents" .md
    fi
}

install_codex() {
    if [ "$PROJECT" -eq 1 ]; then
        link_skills "$PROJECT_DIR/.agents/skills"
        agents_dir="$PROJECT_DIR/.codex/agents"
    else
        link_skills "$AGENTS_SKILLS_DIR"
        agents_dir="$CODEX_DIR/agents"
    fi
    for tmpl in "$ADAPTERS_DIR"/codex/agents/*.toml.tmpl; do
        render_codex_agent "$tmpl" "$agents_dir/$(basename "$tmpl" .tmpl)"
    done
}

install_gemini() {
    if [ "$PROJECT" -eq 1 ]; then
        link_skills "$PROJECT_DIR/.agents/skills"
        link_agents "$ADAPTERS_DIR/gemini/agents" "$PROJECT_DIR/.gemini/agents" .md
    else
        link_skills "$AGENTS_SKILLS_DIR"
        link_agents "$ADAPTERS_DIR/gemini/agents" "$GEMINI_DIR/agents" .md
    fi
}

install_copilot() {
    if [ "$PROJECT" -eq 1 ]; then
        link_skills "$PROJECT_DIR/.agents/skills"
        for agent in "$ADAPTERS_DIR"/copilot/agents/*.agent.md; do
            copy_generated "$agent" "$PROJECT_DIR/.github/agents/$(basename "$agent")"
        done
    else
        link_skills "$AGENTS_SKILLS_DIR"
        link_agents "$ADAPTERS_DIR/copilot/agents" "$COPILOT_DIR/agents" .agent.md
    fi
}

for harness in $HARNESSES; do
    log "== $harness"
    case "$harness" in
        claude-code) install_claude_code ;;
        codex) install_codex ;;
        gemini) install_gemini ;;
        copilot) install_copilot ;;
        *) warn "unknown harness: $harness (use claude-code, codex, gemini, or copilot)" ;;
    esac
done

if [ "$status" -eq 0 ]; then
    log ""
    log "Done. Start a new session of your harness, then run sdlc-setup in a repository."
fi
exit "$status"
