#!/bin/sh
# Remove what install.sh installed: links into this repository, and files that the
# script generated. Nothing else is touched.
#
# usage: uninstall.sh [--project] [--dry-run]
set -eu

REPO_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
MARKER="generated by sdlc-crew install.sh"
DRY_RUN=0
PROJECT=0

while [ $# -gt 0 ]; do
    case "$1" in
        --project) PROJECT=1; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) sed -n '2,6p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) printf 'unknown argument: %s\n' "$1" >&2; exit 2 ;;
    esac
done

log() {
    printf '%s\n' "$*"
}

remove() {
    if [ "$DRY_RUN" -eq 1 ]; then
        log "would remove: $1"
    else
        rm -f "$1"
        log "removed: $1"
    fi
}

clean_dir() {
    dir="$1"
    [ -d "$dir" ] || return 0
    for entry in "$dir"/*; do
        [ -e "$entry" ] || [ -L "$entry" ] || continue
        if [ -L "$entry" ]; then
            case "$(readlink "$entry")" in
                "$REPO_DIR"/*) remove "$entry" ;;
            esac
        elif [ -f "$entry" ] && head -1 "$entry" | grep -q "$MARKER"; then
            remove "$entry"
        fi
    done
}

if [ "$PROJECT" -eq 1 ]; then
    P=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
    for dir in "$P/.claude/skills" "$P/.claude/agents" "$P/.agents/skills" \
        "$P/.codex/agents" "$P/.gemini/agents" "$P/.github/agents"; do
        clean_dir "$dir"
    done
else
    CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
    CODEX_DIR="${CODEX_HOME:-$HOME/.codex}"
    for dir in "$CLAUDE_DIR/skills" "$CLAUDE_DIR/agents" "$HOME/.agents/skills" \
        "$CODEX_DIR/agents" "$HOME/.gemini/skills" "$HOME/.gemini/agents" \
        "$HOME/.copilot/skills" "$HOME/.copilot/agents"; do
        clean_dir "$dir"
    done
fi
log "Done."
