#!/usr/bin/env bash
# Install into a temporary home directory for every harness, check the result, then
# uninstall and check that the home directory is clean. Also test --project.
set -euo pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
status=0

fail() {
    echo "FAIL: $*" >&2
    status=1
}

expect_link() {
    if [ -L "$1" ] && [ "$(readlink "$1")" = "$2" ]; then
        echo "ok: link $1"
    else
        fail "expected a link at $1 to $2"
    fi
}

expect_generated() {
    if [ -f "$1" ] && head -1 "$1" | grep -q "generated by sdlc-crew install.sh"; then
        echo "ok: generated $1"
    else
        fail "expected a generated file at $1"
    fi
}

expect_absent() {
    if [ -e "$1" ] || [ -L "$1" ]; then
        fail "expected nothing at $1"
    else
        echo "ok: absent $1"
    fi
}

SKILLS=(sdlc-crew sdlc-setup sdlc-architect sdlc-engineer sdlc-qa sdlc-ux sdlc-review)
PERSONAS=(sdlc-architect sdlc-engineer sdlc-qa sdlc-ux)

export HOME="$TMP/home"
mkdir -p "$HOME/.claude" "$HOME/.codex" "$HOME/.gemini" "$HOME/.copilot"
unset CLAUDE_CONFIG_DIR CODEX_HOME

echo "== user install, all harnesses detected"
"$REPO_DIR/install.sh"

for s in "${SKILLS[@]}"; do
    expect_link "$HOME/.claude/skills/$s" "$REPO_DIR/skills/$s"
    expect_link "$HOME/.agents/skills/$s" "$REPO_DIR/skills/$s"
done
for p in "${PERSONAS[@]}"; do
    expect_link "$HOME/.claude/agents/$p.md" "$REPO_DIR/adapters/claude-code/agents/$p.md"
    expect_link "$HOME/.gemini/agents/$p.md" "$REPO_DIR/adapters/gemini/agents/$p.md"
    expect_link "$HOME/.copilot/agents/$p.agent.md" "$REPO_DIR/adapters/copilot/agents/$p.agent.md"
    expect_generated "$HOME/.codex/agents/$p.toml"
done

echo "== the rendered Codex agent holds the skill body and no template markers"
if grep -q '@@' "$HOME/.codex/agents/sdlc-architect.toml"; then
    fail "sdlc-architect.toml still holds a template marker"
fi
grep -q "^name = \"sdlc-architect\"" "$HOME/.codex/agents/sdlc-architect.toml" || fail "sdlc-architect.toml has no name"
grep -q "developer_instructions = '''" "$HOME/.codex/agents/sdlc-architect.toml" || fail "sdlc-architect.toml has no developer_instructions"
grep -q "## Step 1" "$HOME/.codex/agents/sdlc-architect.toml" || fail "sdlc-architect.toml does not hold the skill body"

echo "== a second install is idempotent"
"$REPO_DIR/install.sh" > "$TMP/second.log"
grep -q "current:" "$TMP/second.log" || fail "second install did not report current links"

echo "== an existing file is not replaced"
rm "$HOME/.claude/skills/sdlc-qa"
mkdir "$HOME/.claude/skills/sdlc-qa"
if "$REPO_DIR/install.sh" --harness claude-code >/dev/null 2>"$TMP/err"; then
    fail "install did not report the conflict"
fi
grep -q "skipped: $HOME/.claude/skills/sdlc-qa" "$TMP/err" || fail "conflict message missing"
[ -d "$HOME/.claude/skills/sdlc-qa" ] && [ ! -L "$HOME/.claude/skills/sdlc-qa" ] || fail "the existing directory was replaced"
rmdir "$HOME/.claude/skills/sdlc-qa"

echo "== dry run changes nothing"
rm "$HOME/.claude/skills/sdlc-crew"
"$REPO_DIR/install.sh" --harness claude-code --dry-run > "$TMP/dry.log"
grep -q "would:" "$TMP/dry.log" || fail "dry run printed no plan"
expect_absent "$HOME/.claude/skills/sdlc-crew"

echo "== uninstall leaves the home directory clean"
"$REPO_DIR/uninstall.sh"
for s in "${SKILLS[@]}"; do
    expect_absent "$HOME/.claude/skills/$s"
    expect_absent "$HOME/.agents/skills/$s"
done
for p in "${PERSONAS[@]}"; do
    expect_absent "$HOME/.claude/agents/$p.md"
    expect_absent "$HOME/.codex/agents/$p.toml"
    expect_absent "$HOME/.gemini/agents/$p.md"
    expect_absent "$HOME/.copilot/agents/$p.agent.md"
done

echo "== project install"
PROJECT="$TMP/project"
mkdir -p "$PROJECT"
git -C "$PROJECT" init -q
printf 'models:\n  plan: strong-model\n  build: inherit\n  review: strong-model\n' > "$PROJECT/.sdlc-crew.yaml"
(cd "$PROJECT" && "$REPO_DIR/install.sh" --project --harness claude-code --harness codex --harness gemini --harness copilot)
for s in "${SKILLS[@]}"; do
    expect_link "$PROJECT/.claude/skills/$s" "$REPO_DIR/skills/$s"
    expect_link "$PROJECT/.agents/skills/$s" "$REPO_DIR/skills/$s"
done
for p in "${PERSONAS[@]}"; do
    expect_link "$PROJECT/.claude/agents/$p.md" "$REPO_DIR/adapters/claude-code/agents/$p.md"
    expect_link "$PROJECT/.gemini/agents/$p.md" "$REPO_DIR/adapters/gemini/agents/$p.md"
    expect_generated "$PROJECT/.codex/agents/$p.toml"
    expect_generated "$PROJECT/.github/agents/$p.agent.md"
done
grep -q '^model = "strong-model"' "$PROJECT/.codex/agents/sdlc-architect.toml" || fail "the plan model from .sdlc-crew.yaml is not in the architect agent"
if grep -q '^model = ' "$PROJECT/.codex/agents/sdlc-engineer.toml"; then
    fail "the engineer agent has a model line although build is inherit"
fi
(cd "$PROJECT" && "$REPO_DIR/uninstall.sh" --project)
for p in "${PERSONAS[@]}"; do
    expect_absent "$PROJECT/.codex/agents/$p.toml"
    expect_absent "$PROJECT/.github/agents/$p.agent.md"
done

if [ "$status" -eq 0 ]; then
    echo "All install tests passed."
fi
exit "$status"
